spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=admin-service
spring.cloud.gateway.routes[1].uri=lb://admin-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/admin/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/