spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=admin-service
spring.cloud.gateway.routes[1].uri=lb://admin-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/admin/**
spring.cloud.gateway.routes[5].id=wishlist-service
spring.cloud.gateway.routes[5].uri=lb://wishlist-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/wishlist/**
spring.cloud.gateway.routes[6].id=customer-service
spring.cloud.gateway.routes[6].uri=lb://customer-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/customers/**
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/